version: "3.4"

name: yudao-dev-env

services:
  mysql:
    container_name: yudao-mysql-dev
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ruoyi-vue-pro
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql/
      # 自动挂载并执行 SQL 初始化脚本
      - ./sql/mysql/ruoyi-vue-pro.sql:/docker-entrypoint-initdb.d/ruoyi-vue-pro.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: yudao-redis-dev
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: